-- Criação do Banco
CREATE DATABASE MapaSala;

-- Utilização do Banco
USE MapaSala;

-- Criação das Tabelas
CREATE TABLE IF NOT EXISTS Area (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Cor VARCHAR(25) NOT NULL,
  Tipo VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Curso (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Nome VARCHAR(100) NOT NULL,
  Sigla VARCHAR(4) NOT NULL,
  AreaID INT NOT NULL,
  FOREIGN KEY (AreaID) REFERENCES Area(ID)
);

CREATE TABLE IF NOT EXISTS Docente (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Nome VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Turma (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Nome VARCHAR(100) NOT NULL,
  Oferta INT NOT NULL,
  CursoID INT,
  DocenteID INT,
  FOREIGN KEY (DocenteID) REFERENCES Docente(ID),
  FOREIGN KEY (CursoID) REFERENCES Curso(ID)
);

CREATE TABLE IF NOT EXISTS Sala (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Cor VARCHAR(25) NOT NULL,
  Tipo VARCHAR(50) NOT NULL,
  Capacidade INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Reserva (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Inicio DATE NOT NULL,
  Fim DATE NOT NULL,
  Periodo ENUM ('Manhã', 'Tarde', 'Noite'),
  TurmaID INT,
  SalaID INT,
  FOREIGN KEY (TurmaID) REFERENCES Turma(ID),
  FOREIGN KEY (SalaID) REFERENCES Sala(ID)
);

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);
use mapasala;